browser=chrome
google.url=https://www.google.com/
google.search=Orange HRM demo
orangeHrmResult.url=https://orangehrm.com/

#form fields
orangeHrm.name=Vikram Rathode
orangeHrm.phone=1234567890
orangeHrm.jobTitle=Fresher
orangeHrm.companyName=Cognizant
orangeHrm.country=India
orangeHrm.noOfEmployees=11 - 50
orangeHrm.email=rathodeitsolutions@gmail.com
orangeHrm.message=.....